Rise-Vision/rise-cache-v2

gulpfile.js
server.js
test/test-server.js

* Listen for requests at localhost:9494.
* Don't lint test files.
* Need to close server in tests so that tests finish.

Listen for requests at localhost:9494

---

app/helpers/file-system.js
config/config.js

@donnapep @rodrigopavezi what do you think?

Use path.join

---

app/controllers/file.js
app/routes/file.js
app/server.js
package.json
server.js
test/integration/file-test.js
test/unit/file-test.js

* Integrate `node-http-proxy` library that handles returning file to client.

Add proxy support

---

app/controllers/file.js
app/routes/file.js
test/integration/file-test.js
test/unit/file-test.js

@stulees @donnapep please review. cheers

Implemented reading of headers and sending it when reading file.

---

app/controllers/file.js
app/helpers/file-system.js
app/routes/file.js
app/server.js
config/config.js
gulpfile.js
package.json
test/integration/file-test.js
test/unit/file-system-test.js
test/unit/file-test.js

Created a method for moving the file from download folder to cache folder after its download has finished.
Changed check for file existence to check the cache folder
Added and fixed tests

Implemented the use of a cache folder

---

app/controllers/file.js
app/helpers/file-system.js
app/routes/file.js
app/server.js
package.json
server.js
test/integration/file-test.js
test/unit/file-system-test.js
test/unit/file-test.js

Revert back to using `request` module for downloading files.

Use request module for downloading files

---

app/controllers/file.js
app/middleware/error.js
app/routes/file.js
package.json
test/unit/file-test.js

Used the library send
Introduced a mock library for mocking request and response objects
Test coverage

Implemented the stream of files supporting range

---

app/controllers/file.js
app/controllers/metadata.js
app/routes/file.js
app/routes/metadata.js
config/config.js
package.json
rise-cache.js
test/integration/file-test.js
test/integration/metadata-test.js
test/unit/file-test.js
test/unit/metadata-ctrl-test.js

Implemented the reading of the RiseDisplayNetworkII.ini properties file
Passed the proxy configuration to the request module calls
Implemented handling of errors to connect through the proxy
Implemented handling of the errors to get the file or metadata from the host server. It will return 502 if not possible to connect, 504 if it cannot reach the server and 534 if it gets a 404 from the server.
Added tests and updated existent ones
@stulees please review. cheers

Implemented the support for proxy configuration from player

---

app/app.js
app/helpers/file-system.js
app/helpers/logger/external-logger-bigquery.js
app/helpers/logger/logger.js
app/jobs/cleanup.js
app/server.js
circle.yml
config/config.js
package.json
test/integration/file-test.js
test/integration/metadata-test.js
test/integration/ping-test.js
test/integration/server-test.js
test/unit/cleanup-test.js
test/unit/external-logger-bigquery-test.js
test/unit/file-system-test.js
test/unit/logger-test.js

- Created a Logger module which can log info, error and warnings to console, file and external logger
- Created an external logger which log events to BQ using the bqClient from electron common
- Test coverage
- Bumped version

Implemented Rise Cache Logging

---

app/app.js
app/helpers/file-system.js
package.json
test/integration/ping-test.js
test/unit/file-system-test.js

Implemented the cleanup of the log file on app startup.

---

package.json

@donnapep @stulees please review.

Upgraded rise-common-electron

---

app/helpers/file-system.js
app/server.js
config/config.js
test/integration/server-test.js
test/unit/file-system-test.js

_shutdown.txt_ is created in `rvplayer/RiseCache`.

Create shutdown.txt on graceful shutdown and delete on startup

---

app/server.js
package.json
test/integration/server-test.js

Reverts Rise-Vision/rise-cache-v2#46

Revert "Logging a warning when RC does not shutdown correctly"

---

app/helpers/file-system.js
app/server.js
config/config.js
test/integration/server-test.js
test/unit/file-system-test.js

Reverts Rise-Vision/rise-cache-v2#45

Revert "Create shutdown.txt on graceful shutdown and delete on startup"

---

app/controllers/file.js
package.json
test/unit/file-test.js

- Removed decoding and now also validating against "googleapis.com%2Fstorage" directly

Remove decoding in isStorageFile function

---

app/controllers/file.js
app/routes/file.js
test/unit/file-test.js

@stulees @donnapep please review. cheers

Implemented the deletion of the incomplete file from download folder

---

app/app.js
app/helpers/file-system.js
test/integration/ping-test.js

Implemented the clean up of the download folder on startup

---

app/controllers/file.js
config/config.js
test/unit/file-test.js

- Setting a 5 minute connection timeout on the download request
- Unit test added

Handling connection timeout for download request

---

app/app.js
app/controllers/data.js
app/middleware/error.js
app/models/data.js
app/routes/spreadsheets.js
test/integration/spreadsheets-test.js
test/unit/data-test.js

Added logger to the spreadsheet router

Implemented the get method for spreadsheet endpoint

---

app/routes/spreadsheets.js
test/integration/spreadsheets-test.js

I have restructured the spreadsheets router so it does not send responses twice which crashes RC. cheers

Implemented the PUT method

---

app/app.js
app/helpers/file-system.js
app/middleware/error.js
test/integration/display-test.js
test/integration/file-test.js
test/integration/metadata-test.js
test/integration/spreadsheets-test.js
test/unit/helpers/file-system-test.js

Added logger to the error middleware

Implemented the generation of the file key based on the file name

---

package.json

bumped version for release

---

app/app.js
app/helpers/logger/external-logger-bigquery.js
app/helpers/logger/logger.js
package.json
test/unit/helpers/logger/external-logger-bigquery-test.js

Passed the fileSystem object to external logger so it can log error to the file
Created tests for that
@stulees @donnapep please review. cheers

Fixed the UnhandledPromiseRejectionWarning

---

config/config.js
package.json

Fixed the defining of os and architecture.

---

app/app.js
app/routes/financial.js
config/config.js
test/data/financial.json
test/integration/financial-test.js

- New Financial database
- New "/financial" route
- Implemented POST operation to save data
- Added integration tests

Add new /financial endpoint and implement POST operation

---

app/routes/financial.js
test/integration/financial-test.js

- Implemented GET operation to retrieve data
- Added integration tests

Implement GET operation for financial endpoint

---

app/controllers/data.js
app/routes/financial.js
app/routes/spreadsheets.js
package.json

Storing route method parameters in global variables may cause an incorrect response or no response to be returned to the client.

Don't store route method parameters in global variables

---

app/routes/financial.js
app/routes/rss.js
app/routes/spreadsheets.js
config/config.js
package.json

@tejohnso @stulees please review. Issue is here https://trello.com/c/T4eT9sAE/3167-2-potential-issue-500-error-on-player.
cheers

Fixed issue where the body parser middleware limit is too small.

---

app/helpers/file-system.js
test/unit/controllers/file-test.js
test/unit/helpers/file-system-test.js

@tejohnso @stulees please review. cheers

Fixed issue with Content-length being a string

---

app/middleware/error.js
package.json

@stulees @tejohnso please review. cheers

Added more details to the middleware error logging

---

app/controllers/file.js
app/helpers/file-system.js
app/routes/file.js
package-lock.json
package.json
test/integration/file-test.js
test/unit/helpers/file-system-test.js

Changed it to call getAvailable space before calling request.
@tejohnso please review. cheers

Fixed the corrupted download of files

---

app/routes/file.js
package.json
test/integration/file-test.js

Added an integration test
@stulees please review. cheers

Added encodeURI to url param for files so it encode special characters

---

app/routes/file.js
test/integration/file-test.js

Fixed encoding by decoding what comes out of the URL parse

---

app/helpers/url-parser.js
app/routes/file.js
app/routes/metadata.js
package.json
test/integration/file-test.js
test/integration/metadata-test.js
test/unit/helpers/url-parser-test.js

@tejohnso @stulees please review. cheers

Removed all url encoding

---

app/controllers/file.js
app/controllers/financials.js
app/helpers/file-system.js
app/routes/file.js
circle.yml
package-lock.json
package.json

Details [here](https://trello.com/c/IQ7D9lca/3638-2-rise-cache-continues-to-work-if-it-cant-determine-disk-space-availability)

Proceed as normal when available space check fails
